### ISSUE TITLE
Can groups treated between `g` and `t` act as controls?

### ISSUE THREAD

**Issue by korenmiklos** [friosavila/csdid_drdid#10]
https://github.com/friosavila/csdid_drdid/blob/89b964f9c5a4eafafe66fd0451d0367ec36412ea/code/csdid.ado#L44

If `gvar' < `j', then that groups in the control will have already been treated by year `j'. Is this a valid control?

**Comment by pedrohcgs** [comment]
groups treated between `g` and `t` should not act as comparison group.  This is because to estimate the ATT at time `t`, we need to use units that have not yet been exposed to treatment by time `t`.
