### ISSUE TITLE
csdid doesn't reproduce itself

### ISSUE THREAD

**Issue by bjwillage** [friosavila/csdid_drdid#18]
Hello,

First, thank you for creating this resource.

Second, I wanted to let you know when I run this command on the same data twice, it does not give the same results. I thought it might be a seed issue, but I've set seed. I wasn't sure what else it could be.  I do get a warning about not having a balanced panel, but I'm guessing that's not the issue.

I'm attaching a log file where I run the same command twice in a row but it gives different main results and different "simple". I can't share the data I'm using though, but maybe the log file is helpful.

I went ahead and used a command provided by Sun and Abraham (2020), so I don't need any help; just wanted to let you know. If I can provide other information though, I can be reached at bwillage@lsu.edu

Thanks,
Barton

[csdid_not_reproduce text.txt](https://github.com/friosavila/csdid_drdid/files/6580071/csdid_not_reproduce.text.txt)

**Comment by friosavila** [comment]
Thank you very much for reporting this.
I ll try to run some examples on my side. And see if I can reproduce this
error.
If you do not mind, I may also send you a smaller code to try replicating
the commands using an alternative code.
Thank you again,
Fernando

**Comment by friosavila** [comment]
Thank Barton
I figure out that the problem had to do with a check I wasn't making when a person uses ivar option. When you do that, it was expected, but not checked, that you have a panel data structure (one observation per Ivar-time combination). 
I have added a new data check that verifies that before getting into the analysis.
Thanks again
Fernando
