### ISSUE TITLE
Wild bootstrap options do not work

### ISSUE THREAD

**Issue by TomWatersEconomics** [friosavila/csdid_drdid#19]
The guide (https://friosavila.github.io/playingwithstata/main_csdid.html) says that there are several wild bootstrap options but they seem to not be coded up; running
`net install csdid, from ("https://raw.githubusercontent.com/friosavila/csdid_drdid/main/code/") replace
use https://friosavila.github.io/playingwithstata/drdid/mpdta.dta, clear
csdid  lemp lpop , ivar(countyreal) time(year) gvar(first_treat) method(dripw) agg(event) saverif(rif_example) wboot replace rseed(1)`

Returns the error
`option rseed() not allowed`

The same outcome occurs if one tries the -wbtype- or -reps- options.

**Comment by friosavila** [comment]
Yes, please use the guide as the provisionary helpfile.
Also, I thin the problem is that the csdid_drdid code is not up to date. Im updating those files now. But it would be far easier if you download them all directly in your computer from my website.
F

**Comment by TomWatersEconomics** [comment]
Thanks Fernando. I have done this, getting the 6 files on your site, which has fixed this problem though that has thrown up another error - I'll make a new ticket.
