### ISSUE TITLE
Stata help file is mainly reghdfe help file

### ISSUE THREAD

**Issue by TomWatersEconomics** [friosavila/csdid_drdid#20]
Everything in the Stata helpfile for csdid is from the reghdfe helpfile, with the exception of the first line of the syntax section and the description section.

See for example below screenshot
![image](https://user-images.githubusercontent.com/88095619/127332502-01494693-af5a-49da-bcb9-d762d36af88f.png)

**Comment by friosavila** [comment]
Hi Tom
Yes, I havent written the help file for csdid yet. and I don't think my colleagues have updated the helpfile on drdid either.
Please use my post and webpage as a helpfile. I ll delete the current file to avoid confusion.
F

**Comment by TomWatersEconomics** [comment]
Thanks Fernando
