### ISSUE TITLE
Bug when not all groups observed every period

### ISSUE THREAD

**Issue by TomWatersEconomics** [friosavila/csdid_drdid#21]
(This error did not occur on the previous version I had downloaded from net install).

At least in some instances, the error "Stopped by user" occurs if one runs csdid on a sample which does not include an observation for every treatment in every time period. This does not seem to be sensitive to what options are in the csdid command. Here is a minimal working example - please see the attached dataset (GitHub will not let me upload .dta, hence uploading .xlsx).

`import excel using "[filepath]\csdidtest.xlsx", clear firstrow`
`csdid inwork , time(q) gvar(treatdate) agg(event)`
`csdid inwork if subsample, time(q) gvar(treatdate) agg(event)`

The second, but not first, csdid will give an error. You can see that the subsample has some treatment group / time period combinations where there are no observations:
`tab q treatdate if subsample`

[csdidtest.xlsx](https://github.com/friosavila/csdid_drdid/files/6893846/csdidtest.xlsx)

**Comment by TomWatersEconomics** [comment]
Agh, I had downloaded it but not uninstalled the previous version so Stata was still looking at that! Sorry! 

Very grateful for your help!

**Comment by friosavila** [comment]
Your welcome
