### ISSUE TITLE
Issue with csdid_plot and csdid_stats

### ISSUE THREAD

**Issue by Mobariz** [friosavila/csdid_drdid#22]
The csdid 1.6 works well for most of it. But I am having issues csdid_stats and csdid_plot. Although I have updated to csdid 1.6 the two auxiliary commands do not work. It says the commands are unrecognized. Is there something else that I need to install to get those two to work?

**Comment by friosavila** [comment]
Did you get them from my site? I think they are not in the list of "installable" files right now. But you can just copy them wherever the others are.
Please let me know if the problem persists after downloading those.

**Comment by Mobariz** [comment]
I thought those two come automatically by updating to csdid 1.6. Do I need to install csdid_plot and csdid_stats separately. Are there similar path as net install csdid, from ("https://raw.githubusercontent.com/friosavila/csdid_drdid/main/code/") replace   ?

**Comment by friosavila** [comment]
No, you need to copy them directly on the same folder as csdid.ado is.
I have modified the installation file, and it may do it on its own now, but
i cannot check that right now.
