### ISSUE TITLE
Universal base period

### ISSUE THREAD

**Issue by bcallaway11** [friosavila/csdid_drdid#29]
Just got a question on the R side about universal base periods but using `csdid`: bcallaway11/did#105.  I thought this would be a better place for that question and that you all might have a better answer than I.

@taiwoakinyemi

Brant

**Comment by bcallaway11** [comment]
@friosavila, that’s great!  Thanks a lot.

**Comment by taiwoakinyemi** [comment]
Thanks so much, Brant and Fernando
I responded on the other post too. Below are my findings. I had to uninstall my previous version and reinstall to use the option "long"
[](https://user-images.githubusercontent.com/57067445/152801481-12fe92ad-9b5c-4673-9d33-3df2c4f16c53.png)[](https://user-images.githubusercontent.com/57067445/152801825-4a115811-4924-4441-a613-2a7471807f1d.png)I was expecting the coefficients for the universal base period to be 0 but it is not.

Another issue I have is the command code, when I used the below command lines I get different results, which is the more appropriate?
csdid wealthscore hheadage under5 i.state, time(syear) gvar(pyear) method(drimp) long saverif(rif) replace
estat all
estat event, window(-5 5)
csdid_plot
image
However, when I used the below command and when I did not specify option(long) the results are similar.
csdid wealthscore hheadage under5 i.state, time(syear) gvar(pyear) method(drimp) option(long) saverif(rif) replace
estat all
estat event, window(-5 5)
csdid_plot
image

**Comment by taiwoakinyemi** [comment]
Thank you so much. The insights are helpful.

**Comment by XiangShawnZhang** [comment]
Hi Fernando, is there any reason why a period pretreatment missing when I use the long2 option? I thought there should be an estimation of period = -3. Thanks! Just for your inference, the base_period = "universal" in R on the same data works.
<img width="1001" alt="Graph1" src="https://user-images.githubusercontent.com/107322624/225457574-5b3fa4d8-da3a-46a4-9677-322da2609638.png">
<img width="1001" alt="Graph2" src="https://user-images.githubusercontent.com/107322624/225457586-60eabc78-2326-44b8-85e9-ffd59307b625.png">

**Comment by friosavila** [comment]
It’s missing bc is zero by construction

**Comment by XiangShawnZhang** [comment]
I am still a bit confused. Do you mean it is also 0 for the period = -3? This is the plot from did package om R. Thanks for your clarification. 
![graph3](https://user-images.githubusercontent.com/107322624/225459167-5bbbed04-e0ad-4578-b3b9-779c8e6ba717.png)

**Comment by friosavila** [comment]
Hmm I think you are using an older version of csdid
If you could update it and plot it again?

**Comment by XiangShawnZhang** [comment]
I think the version of csdid is up to date. I also tried the new csdid2, got the some results. 
![fig1](https://user-images.githubusercontent.com/107322624/225497347-a5c3362d-6b7f-4cc2-9940-a9fd9225730b.png)
![fig2](https://user-images.githubusercontent.com/107322624/225497362-72449cea-adf1-450d-b7a5-b7d2edbc4b9c.png)

**Comment by friosavila** [comment]
Ohh ok
Then the results are correct
Perhaps just one more thing
Did in R and csdid in Stata do things slightly diffferent for pretreatment
Try adding the option “asinr”

**Comment by XiangShawnZhang** [comment]
Thanks @friosavila! Regrettably, the addition of "asinr" does not yield the desired outcome. Although it produces a distinct estimation for the pretreatment phase, the analysis is still limited to a single period of estimation.
![截屏2023-03-16 上午11 44 22](https://user-images.githubusercontent.com/107322624/225674421-cdec7155-3365-4ecb-8c59-22db93ddbe7d.png)
