### ISSUE TITLE
Use same interface as `didregress`

### ISSUE THREAD

**Issue by korenmiklos** [friosavila/csdid_drdid#3]
It would ease user adoption if `csdid` and `drdid` had the same option names and the exact same interface as `didregress`, the official Stata command.

**Comment by friosavila** [comment]
since didregress is quite different from what this does, we may have more freedom to adjust the syntax. 
For now, the only think I really want is to have a more standard way of calling options.
```
command depvar indepvar, options
```

**Comment by korenmiklos** [comment]
Consistency is important for users. I don't know how well `didregress` is used, I never used it myself. But its syntax,
```
didregress (y1 x1 x2) (treat1), group(grpvar1) time(tvar)
```
seems quite applicable to this case, too.

This is something to decide relatively early (so as not to confuse users), but does not need much change in code.

**Comment by friosavila** [comment]
we can certainly change `ivar` to `group`. But we also want to make this consistent with the R implementation of DID. 
Regarding "treatment" I prefer using it as a separate option. It feels more natural that way. at least to me.

**Comment by korenmiklos** [comment]
Agree on `treatment`, much better to have it as a separate option. `group` sounds better to me than `ivar`, more in line with the naming style of `time`.

**Comment by friosavila** [comment]
I ll ask Enrique about a better way to parse the arguments
That way it may be possible to allow both ways of calling the command
