### ISSUE TITLE
Options not allowed

### ISSUE THREAD

**Issue by nbreg** [friosavila/csdid_drdid#33]
Hi Fernando,

Thanks for making this fantastic package! I have installed it both from SSC and then from your website using net install. In both cases, I run into an error if I try to use some options, particularly agg() or wboot. For example, following your tutorial, this runs successfully:

`use https://friosavila.github.io/playingwithstata/drdid/mpdta.dta, clear

csdid  lemp lpop , ivar(countyreal) time(year) gvar(first_treat) method(dripw)`

However, when I run the following, I get the error `agg not allowed`:

`csdid  lemp lpop , ivar(countyreal) time(year) gvar(first_treat) method(dripw) ///
agg(event) saverif(rif_example) wboot replace rseed(1)`

Further, if I take out the agg, I get `wboot not allowed`.

Any idea what might be the problem?

Thanks!
Nate

**Comment by friosavila** [comment]
Hi Nate
that is very odd. When i do that on my end, it works without problems.
May I suggest try again after updating csdid and drdid with the latest
version from SSC?
Let me know if the problem persists
Fernando

**Comment by nbreg** [comment]
Thanks for the suggestion. I tried deleting the ado files for csdid and drdid and reinstalling from SSC, but still the same errors appear, unfortunately.

**Comment by friosavila** [comment]
So try restart Stata
Also type
which csdid.ado
which drdid.ado
They should say version 1.71 or higher

**Comment by nbreg** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
