### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by korenmiklos** [friosavila/csdid_drdid#4]
Explore open source licenses and add one.

**Comment by korenmiklos** [comment]
The original CRAN packages are [GPL licensed](https://cran.r-project.org/web/licenses/GPL-2). This means

1. We also have to use an open license, in fact, one that does not allow downstream reusers to ever "close" the source code. I suggest going with [GPL-3](https://choosealicense.com/licenses/gpl-3.0/).
2. We must display copyright and license information when the program is run (2.c), unless we claim "the program does not normally display such notices".  

I would be happier with a shorter [MIT license](https://choosealicense.com/licenses/mit/), but this violates no 1, as it does not require anything from downstream users.

**Comment by korenmiklos** [comment]
@pedrohcgs and @bcallaway11 if you agree, we would move to an MIT license. Please respond in a comment for the record.

**Comment by friosavila** [comment]
I’m fine either way 
And I don’t think there is need to display the licensing info every time. None of my other commands do that
