### ISSUE TITLE
Why use `gvar==0` for control group?

### ISSUE THREAD

**Issue by korenmiklos** [friosavila/csdid_drdid#6]
[`csdid` assumes](https://github.com/friosavila/csdid_drdid/blob/61c35f42f87309c6759a4dda236481df81f5d63f/code/csdid.ado#L34) that `gvar==0` denotes never treated units. This may not be true in all applications, maybe use a separate tag for control cases?

**Comment by friosavila** [comment]
Right, that is how -did- operates as well. Units that are never treated have a -gvar- equal to 0. So they are part of the baseline group.

**Comment by korenmiklos** [comment]
Yes, but 0 could be a valid time in some settings, in which case this would lead to a bug. Those treated at 0 will be take as never treated.

I typically use
```
egen first_time_treated = min(cond(treated, year, .)), by(unit)
```
for which never-treated units have `first_time_treated==.`. But this is another special case. It's probably best to set a flag for this among command options.
